version: '3.8'

services:
  backend:
    build:
      context: ./backend/StockApp/StockApp 
    container_name: backend-container
    ports:
      - "8080:8080" 
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app-network
    volumes:
      - ./backend/StockApp/StockApp/src/main/resources/scripts:/app/scripts

  frontend:
    build:
      context: ./frontend/my-app 
    container_name: frontend-container
    ports:
      - "80:80" 
    depends_on:
      - backend 
    networks:
      - app-network
    environment:
      - REACT_APP_API_URL=http://localhost:8080

networks:
  app-network:
    driver: bridge

volumes:
  scripts:
